#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "qui"
name = "Qui"
description.en = "qBittorrent web UI"
description.fr = "Interface utilisateur Web qBittorrent"

version = "1.13.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0"
website = "https://getqui.com/"
admindoc = "https://getqui.com/docs/intro"
code = "https://github.com/autobrr/qui"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
     in_subdir = false
    amd64.url = "https://github.com/autobrr/qui/releases/download/v1.13.1/qui_1.13.1_linux_x86_64.tar.gz"
    amd64.sha256 = "231de1865f46ce3cee3c2909401c3fb302077d8c8ffed27cd7e2d48e039d152e"
    arm64.url = "https://github.com/autobrr/qui/releases/download/v1.13.1/qui_1.13.1_linux_arm64.tar.gz"
    arm64.sha256 = "99cd052b06c06737f541797f444f9842acb4b021c48e0ff7961077046a63ffb1"
    armhf.url = "https://github.com/autobrr/qui/releases/download/v1.13.1/qui_1.13.1_linux_x86_64.tar.gz"
    armhf.sha256 = "99fb028b047dc11d4104a50fb1c623a5e269557874b16663ba153b4f6e54c571"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_linux_x86_64.tar.gz"
    autoupdate.asset.armhf = ".*_linux_x86_64.tar.gz"
    autoupdate.asset.arm64 = ".*_linux_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
